### ISSUE TITLE
`fetch` from `load` event should only be used when the client is initialized on the server.

### ISSUE THREAD

**Issue by vishalbalaji** [icflorescu/trpc-sveltekit#59]
**Describe the bug**

This issue is somewhat of a sequel to #54, which suggested that the `fetch` function provided by the `load` function be used, leading to the change in `trpc-sveltekit@3.2.5`. This works well and good when the client is created in `+page.ts` using `event`, which provides a `fetch` implementation. However, the client is initialized using `$page` in `.svelte` files, which does not have the `fetch` implementation. 

**`init` from server**

```javascript
{
  url: URL {
    href: 'http://localhost:5173/',
    origin: 'http://localhost:5173',
    protocol: 'http:',
    username: '',
    password: '',
    host: 'localhost:5173',
    hostname: 'localhost',
    port: '5173',
    pathname: '/',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  params: {},
  data: null,
  route: { id: '/' },
  fetch: [AsyncFunction (anonymous)], // <-- This his `fetch`
  setHeaders: [Function: setHeaders],
  depends: [Function: depends],
  parent: [AsyncFunction: parent]
}
```
**`init` from client**

```javascript
// this does not
{
  error: null,
  params: {},
  route: { id: '/' },
  status: 200,
  url: URL {
    href: 'http://localhost:5173/',
    origin: 'http://localhost:5173',
    protocol: 'http:',
    username: '',
    password: '',
    host: 'localhost:5173',
    hostname: 'localhost',
    port: '5173',
    pathname: '/',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  data: {},
  form: null
}

```

So, when `fetch` is de-structured from `init` [in this line](https://github.com/icflorescu/trpc-sveltekit/blob/db84d6ff064d05994984153e3a03051a95998c5c/package/src/client.ts#L51), it is `undefined`. I guess this causes `sveltekit` to default to whatever fetch is available instead of the fetch provided by `sveltekit`, causing errors such as in the screenshot below.

I am not entirely sure about this, but it seems as though `sveltekit` handles  which `fetch` to use automatically on the client side, but overriding it manually with `undefined` is what causes this behaviour. This should be easily fixed by only overriding `fetch` if it is initialized on the server with a check similar to [this](https://github.com/icflorescu/trpc-sveltekit/blob/db84d6ff064d05994984153e3a03051a95998c5c/package/src/client.ts#L55).

**To Reproduce**
1.  Setup `trpc-sveltekit` as per docs.
2. Create simple function calling a `trpc` procedure.

**Expected behavior**
There should be no warnings or errors thrown informing the user that  the `fetch` from `load` should be user.

**Screenshots**
![2023-01-31_18:21:01_scrot](https://user-images.githubusercontent.com/36506250/215766334-15a3e668-d2d2-477b-b979-98da01d3e41f.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 109.0

**Comment by icflorescu** [comment]
I am unable to reproduce the behavior.
Can you please provide a codesandbox or something like that?
Thanks a lot!

**Comment by vishalbalaji** [comment]
That's interesting.... It is not reproducible using the example in your `README` where you reload the data by clicking on a link. However, if you just call it using `{#await}` in the template, it produces this error.

[Here is a codesandbox](https://codesandbox.io/p/sandbox/quiet-worker-myvekk?file=%2Fsrc%2Froutes%2F%2Bpage.svelte&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A16%7D%5D) with this problem setup, although to be honest, I have never used codesandbox before and found it a little cumbersome. You would have to open the preview in a different tab and have the console open, where you can see the error. It might just be easier to clone my example locally and run it from here: https://github.com/vishalbalaji/trpc-sveltekit-issue-59.

**Comment by icflorescu** [comment]
Ah, I see now.
Interestingly enough, I only see this the warning in Firefox, and only in the circumstances you've provided (using with `{#await}` in the template). Chrome (Brave/Edge) says nothing.
I think `v3.2.7` should fix it.

Be careful, though - in the example you provided, make sure to change your `$lib/trpc/client.ts` to something like this:

```ts
import type { Router } from '$lib/trpc/router';
import { createTRPCClient, type TRPCClientInit } from 'trpc-sveltekit';

export function trpc(init?: TRPCClientInit) {
  return createTRPCClient<Router>({ init });
}
```

I the docs/quickstart I wrote, I did not consider using it with `#{await}`, that's why when calling the function in the browser I was reusing the same "cached" client instance initialized like this: `browserClient = createTRPCClient<Router>();`...

I'll probably have to rewrite that part of the documentation at some point.

**Comment by icflorescu** [comment]
@vishalbalaji I'm curious to see what's your opinion on this...

**Comment by icflorescu** [comment]
Apparently dealing with some post-covid-induced brain-fog here :-)
I've discovered another error in the last commit and ended up partially reverting the `3.2.4 -> 3.2.5` one.
Try to update to the latest version (currently `v3.2.9`).

**Comment by vishalbalaji** [comment]
Oof, I feel you. But yeah, `v3.2.9` fixes it. Like mentioned before, the Firefox warning still exists, but it doesn't seem to be coming from `trpc-sveltekit`. I'll probably have to raise an issue with `trpc` or `sveltejs/kit` if I figure out where it is coming from.

Anyway, thanks for all this amazing work!
